

export default [
    {
        name        : 'Llucaitx',
        code        : 'FV-LLUC',
        location    : 'fv_llucaitx_location',
        type        : 'fv_llucaitx_type',
        power       : 'fv_llucaitx_power',
        area        : 'fv_llucaitx_area',
        module      : 'fv_llucaitx_module',
        state       : 'fv_llucaitx_state',
        active      : false,
    },
    {
        name        : 'Tornaltí',
        code        : 'FV-TORN',
        location    : 'fv_tornalti_location',
        type        : 'fv_tornalti_type',
        power       : 'fv_tornalti_power',
        area        : 'fv_tornalti_area',
        module      : 'fv_tornalti_module',
        state       : 'fv_tornalti_state',
        active      : false,
    },
    {
        name        : 'Edumar',
        code        : 'FV-Edumar',
        location    : 'fv_edumar_location',
        type        : 'fv_edumar_type',
        power       : 'fv_edumar_power',
        area        : 'fv_edumar_area',
        module      : 'fv_edumar_module',
        state       : 'fv_edumar_state',
        active      : true,
    },
    {
        name        : 'El Raurell 1',
        code        : 'FV-ER1',
        location    : 'fv_raurell1_location',
        type        : 'fv_raurell1_type',
        power       : 'fv_raurell1_power',
        area        : 'fv_raurell1_area',
        module      : 'fv_raurell1_module',
        state       : 'fv_raurell1_state',
        active      : true,
    },
    {
        name        : 'El Raurell 2',
        code        : 'FV-ER2',
        location    : 'fv_raurell2_location',
        type        : 'fv_raurell2_type',
        power       : 'fv_raurell2_power',
        area        : 'fv_raurell2_area',
        module      : 'fv_raurell2_module',
        state       : 'fv_raurell2_state',
        active      : true,
    },
    {
        name        : 'La Parera',
        code        : 'FV-LP',
        location    : 'fv_parera_location',
        type        : 'fv_parera_type',
        power       : 'fv_parera_power',
        area        : 'fv_parera_area',
        module      : 'fv_parera_module',
        state       : 'fv_parera_state',
        active      : true,
    },
    {
        name        : 'Cal Costet',
        code        : 'FV-CC',
        location    : 'fv_costet_location',
        type        : 'fv_costet_type',
        power       : 'fv_costet_power',
        area        : 'fv_costet_area',
        module      : 'fv_costet_module',
        state       : 'fv_costet_state',
        active      : true,
    },
    {
        name        : 'Molí',
        code        : 'FV-MOLI',
        location    : 'fv_moli_location',
        type        : 'fv_moli_type',
        power       : 'fv_moli_power',
        area        : 'fv_moli_area',
        module      : 'fv_moli_module',
        state       : 'fv_moli_state',
        active      : true,
    }
];